jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres-postgresql
      user: postgres
      password: 12345
      port: 5432
      dbname: postgres
      schema: public
      threads: 1
